/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/sections/AboutSection.vue')['default']
    ContactSection: typeof import('./src/components/sections/ContactSection.vue')['default']
    EducationSection: typeof import('./src/components/sections/EducationSection.vue')['default']
    ExperienceSection: typeof import('./src/components/sections/ExperienceSection.vue')['default']
    FooterBar: typeof import('./src/components/layout/FooterBar.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    SkillsSection: typeof import('./src/components/sections/SkillsSection.vue')['default']
  }
}
