import sharp from 'sharp';
import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const INPUT_DIR = 'public/images';
const files = (await readdir(INPUT_DIR)).filter((f) => f.match(/^travel\d+\.webp$/));

// width → webp quality: smaller sizes can afford higher quality (smaller file anyway)
const SIZES = [
  { w: 400, quality: 80 },
  { w: 800, quality: 65 },
];

if (files.length) {
  for (const file of files) {
    const base = file.replace('.webp', '');
    const src = join(INPUT_DIR, file);
    const { width } = await sharp(src).metadata();

    for (const { w, quality } of SIZES) {
      const dest = join(INPUT_DIR, `${base}-${w}w.webp`);

      if (width <= w) {
        console.log(`⏩  ${file} is already ≤${w}px wide, skipping`);
        continue;
      }

      await sharp(src)
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality, effort: 6 })
        .toFile(dest);

      console.log(`✅  ${dest}`);
    }
  }
  console.log('Resize done.');
} else {
  console.log('No originals found in public/images/ — skipping resize step.');
  console.log(
    'Place original travel photos (travel1.webp etc.) in public/images/ to generate resized versions.',
  );
}

// ── Generate base64 LQIP placeholders from *-800w.webp ───────────────────────
const placeholders = {};
const outputFiles = (await readdir(INPUT_DIR)).filter((f) => f.match(/^travel\d+-800w\.webp$/));

if (!outputFiles.length) {
  console.error('ERROR: No *-800w.webp files found in public/images/. Run resize step first.');
  process.exit(1);
}

for (const file of outputFiles) {
  const base = file.replace('-800w.webp', '');
  const src = join(INPUT_DIR, file);

  const buf = await sharp(src)
    .resize({ width: 16, withoutEnlargement: true })
    .webp({ quality: 20 })
    .toBuffer();

  placeholders[base] = `data:image/webp;base64,${buf.toString('base64')}`;
  console.log(`🖼️   placeholder for ${base} (${buf.length}B)`);
}

const output = [
  '// Auto-generated by scripts/optimize-images.mjs — do not edit manually',
  'export const travelPlaceholders: Record<string, string> = {',
  ...Object.entries(placeholders).map(([k, v]) => `  '${k}': '${v}',`),
  '};',
].join('\n');

await writeFile('src/assets/travel-placeholders.ts', output, 'utf8');
console.log('✅  src/assets/travel-placeholders.ts written');
