// Auto-generated by scripts/optimize-images.mjs — do not edit manually
export const travelPlaceholders: Record<string, string> = {
  travel1:
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwBACdASoQABwAPzmEuVOvKKWisAgB4CcJYwDE2CLMmn2+xY9u6MSa8fxegAD+SQDan1cGo93YDGd6PfQGdNnr1nkE0ySfTW4HxovF+eEDjLiDMMiHF7vLAWRZa4RqyOCltfXTd+W0sxo0AAA=',
  travel2:
    'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABwAPzmGuVOvKSWisAgB4CcJZgAAWmA9ah8+gygnQTDAAPjhVDOfx5rATbSTgDUpihXu+0TrHrpd2V3eFEt2rQ9unztR1LZFcZiEMCShnKQO5ZwNy4mjyuaePSxskDo0vl2+ZypneFa8nsZAyyCS70HHI0MKuolwb8BV1SI10iAOtkeIJj0psAA=',
  travel3:
    'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoQABwAPzmGuVOvKSWisAgB4CcJYwC/OCHgTfgSfk/xDAv0HsgAAP6uoSZr3eQC48BtJ7cpP5XdAGuHH1mZH+mJIVJFuGIAcKq24oO4MGCXelzAxxlqpK1febUTBsSaTNU7TspCZetiW/JPNmQwZRUIvQAAAA==',
};
